# Generated by Django 4.1.3 on 2024-02-20 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('author', models.CharField(max_length=100)),
                ('illustrator', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=250)),
                ('uid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='graphicsphereapi.novel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphicsphereapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='NovelGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novels', to='graphicsphereapi.genre')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='graphicsphereapi.novel')),
            ],
        ),
        migrations.AddField(
            model_name='novel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphicsphereapi.user'),
        ),
    ]
